language: node_js
node_js:
    - "5.0.0"
sudo: required
dist: trusty
addons:
    firefox: "41.0"
cache:
    directories:
        - node_modules
before_install:
    - gem install sass
before_script:
    - export DISPLAY=:99.0
    # - Xvfb :99 -ac -screen 0 1280x1024x16 &
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1680x16
    # - "sh -e /etc/init.d/xvfb start"
    - sleep 5
    - npm start

script:
#     # - eslint --ext .jsx src
#     # - eslint --ext .js src
    - npm test
# after_success:
#     - echo '!!! 開始佈署 !!!'
#     #########
#     - echo '!!! 成功佈署 !!!'